# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 
#  terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

eerste = 1
tweede = 2
res = 2
while (eerste+tweede < 4000000):
    temp = eerste + tweede
    eerste = tweede
    tweede = temp
    if tweede % 2 == 0:
        res += tweede

print(res)